
package org.fkjava.cxf.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloWorldWs", targetNamespace = "http://impl.ws.cxf.fkjava.org/", wsdlLocation = "http://127.0.0.1/crazyit?wsdl")
public class HelloWorldWs
    extends Service
{

    private final static URL HELLOWORLDWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.fkjava.cxf.ws.HelloWorldWs.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.fkjava.cxf.ws.HelloWorldWs.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1/crazyit?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1/crazyit?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOWORLDWS_WSDL_LOCATION = url;
    }

    public HelloWorldWs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldWs() {
        super(HELLOWORLDWS_WSDL_LOCATION, new QName("http://impl.ws.cxf.fkjava.org/", "HelloWorldWs"));
    }

    /**
     * 
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldWsPort")
    public HelloWorld getHelloWorldWsPort() {
        return super.getPort(new QName("http://impl.ws.cxf.fkjava.org/", "HelloWorldWsPort"), HelloWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldWsPort")
    public HelloWorld getHelloWorldWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.cxf.fkjava.org/", "HelloWorldWsPort"), HelloWorld.class, features);
    }

}
